version: '3'
services:
  php:
    build: ./.docker/php/
    volumes:
      - .:/var/www/app
      - ./.docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini